### ISSUE TITLE
Add OSCA Lomé chapter as oss community in western africa

### ISSUE THREAD

**Issue by geoffreylgv** [Everything-Open-Source/open-source-communities-in-africa#8]
Hi @mesrenyamedogbe, hope you are doing great, thank you for this amazing work.
Can I add OSCA Lomé Chapter as oss community in Western Africa ?
If so, kindly assign it to me, thanks.

**Comment by mesrenyamedogbe** [comment]
Hello Geoffrey, please feel free to add your community!

**Comment by geoffreylgv** [comment]
> Hello Geoffrey, please feel free to add your community!

Alright 👌🏾

**Comment by mesrenyamedogbe** [comment]
Just adding that you should take a look at the contributing guideline here https://github.com/Everything-Open-Source/open-source-communities-in-africa/blob/main/contributing.md before you make the addition. Thank you!

**Comment by geoffreylgv** [comment]
> Just adding that you should take a look at the contributing guideline here https://github.com/Everything-Open-Source/open-source-communities-in-africa/blob/main/contributing.md before you make the addition. Thank you!

Yeah sure, thank you for the precision
